// ═══════════════════════════════════════════════════════════════════════════
// GAME CONSTANTS — extracted from page.tsx for maintainability
// ═══════════════════════════════════════════════════════════════════════════

import type { Injury, Item, AntagonistClue } from '@/lib/gameTypes'

// ═══════════════════════════════════════════════════════════════════════════
// AI MODEL CONFIGURATION — OpenRouter fallback chain (free-tier models only)
// ═══════════════════════════════════════════════════════════════════════════

export const OPENROUTER_MODEL = 'openai/gpt-oss-120b:free'

export const OPENROUTER_MODEL_TOKEN_LIMITS: Record<string, number> = {
  'openai/gpt-oss-120b:free': 131072,
  'qwen/qwen3-next-80b-a3b-instruct:free': 262144,
  'nvidia/nemotron-3-super-120b-a12b:free': 262144,
  'meta-llama/llama-3.3-70b-instruct:free': 65536,
}

export const OPENROUTER_FALLBACK_MODELS = [
  'openai/gpt-oss-120b:free',
  'qwen/qwen3-next-80b-a3b-instruct:free',
  'nvidia/nemotron-3-super-120b-a12b:free',
  'meta-llama/llama-3.3-70b-instruct:free',
]

// ═══════════════════════════════════════════════════════════════════════════
// SHARD TYPES - Artifacts from all DDG 1980 pantheons
// ═══════════════════════════════════════════════════════════════════════════

export const SHARD_NAMES = [
  // Original shards
  { name: 'Pale Shard', origin: 'A shepherd found it in a field three hundred years ago and kept it in a box not knowing why. It is warm to the touch. It has always been warm to the touch.', color: '#e8e0d0', glow: 'rgba(220,210,180,.6)', pantheon: 'Primordial', power: 'Favors any god' },
  { name: 'First Crack', origin: 'Every mythology has a word for it, and they all disagree about what it means. The Norse say it is where Yggdrasil first split. The Greeks say it is older than Yggdrasil. Both are right. Neither is right.', color: '#d0d8e8', glow: 'rgba(180,195,220,.6)', pantheon: 'Primordial', power: 'Favors chaotic gods' },
  { name: 'Splinter of Before', origin: 'Before the gods. Before the myths. Before belief gave things names, this existed. It is not a piece of something. It is a piece of when something had not yet decided what to be.', color: '#e0d0e8', glow: 'rgba(200,175,220,.6)', pantheon: 'Primordial', power: 'Favors elder gods' },
  { name: 'Yggdrasil Wound', origin: 'Not a shard. A wound in the world-tree that never closed, mistaken by later scholars for a shard because the mind requires things to have edges. It has no edges. It only looks like it does.', color: '#d0e8d5', glow: 'rgba(160,210,170,.6)', pantheon: 'Norse', power: 'Favors Norse pantheon' },
  // Greek/Roman shards
  { name: 'Eye of Cronos', origin: 'When Zeus overthrew his father, a single eye fell from Cronos\'s crown and became this shard. It remembers being part of something that ruled before the Olympians. It wants to rule again.', color: '#f0d080', glow: 'rgba(220,180,80,.6)', pantheon: 'Greek', power: 'Favors Greek Titans and Olympians' },
  { name: 'Gorgon\'s Tear', origin: 'Medusa wept once, before her curse, before her monstrosity. This crystallized tear holds that moment—when she was still beautiful, still mortal, still capable of grief. It is the saddest thing in existence.', color: '#80c080', glow: 'rgba(80,180,80,.6)', pantheon: 'Greek', power: 'Favors chthonic gods' },
  // Egyptian shards
  { name: 'Feather of Ma\'at', origin: 'When Anubis weighs hearts against the feather of truth, sometimes the heart is heavier. Sometimes lighter. This shard is the difference—the accumulated weight of every soul ever judged.', color: '#f0f0e0', glow: 'rgba(240,240,200,.6)', pantheon: 'Egyptian', power: 'Favors Egyptian pantheon, bonus to lawful gods' },
  { name: 'First Sunrise', origin: 'Ra\'s first dawn was not gentle. It was violent—the moment when darkness was torn apart and replaced with something that burned. This shard is that tear. It still burns.', color: '#ffa040', glow: 'rgba(255,140,40,.6)', pantheon: 'Egyptian', power: 'Favors Ra and solar deities' },
  // Cthulhu Mythos shards
  { name: 'Dreamer\'s Fragment', origin: 'Cthulhu dreams in R\'lyeh, and those dreams leak into reality. This shard is crystallized nightmare—a dream that escaped and forgot how to end. Touching it feels like drowning in sleep.', color: '#6080a0', glow: 'rgba(80,100,140,.6)', pantheon: 'Cthulhu', power: 'Favors Great Old Ones, high risk of summoning hostile entities' },
  { name: 'Nameless Mist', origin: 'Before names, there was mist. The mist that spawned Cthulhu, that spawned Nyarlathotep. This is a piece of that primordial fog, compressed into something almost solid, almost real, almost safe.', color: '#9070a0', glow: 'rgba(130,90,140,.6)', pantheon: 'Cthulhu', power: 'Favors Outer Gods' },
  // Melnibonéan shards
  { name: 'Black Rune Shard', origin: 'Elric of Melniboné carried Stormbringer, and Stormbringer fed on souls. This shard is what remains of the first soul the black blade ever consumed. It is still screaming.', color: '#403050', glow: 'rgba(60,40,70,.6)', pantheon: 'Melnibonéan', power: 'Favors Chaos Lords (Arioch, Xiombarg)' },
  { name: 'Last Dragon\'s Heart', origin: 'When the last dragon of Melniboné died, its heart did not stop. It became this shard, still beating, still dreaming of fire and flight and the days when dragons ruled.', color: '#c03030', glow: 'rgba(180,40,40,.6)', pantheon: 'Melnibonéan', power: 'Favors Law (Donblas, Arkyn)' },
  // Nehwon shards
  { name: 'Rat King\'s Crown', origin: 'In the sewers beneath Lankhmar, the Rat King found something. A crown of bone and shadow that made rats obey. The shard broke from that crown. The rats still remember.', color: '#706050', glow: 'rgba(100,80,60,.6)', pantheon: 'Nehwon', power: 'Favors neutral gods and tricksters' },
  { name: 'Skah Jordan Fragment', origin: 'Fafhrd and the Gray Mouser once robbed a temple of something that should not have been there. This shard broke from their prize. The temple\'s god has been searching ever since.', color: '#a09080', glow: 'rgba(150,130,110,.6)', pantheon: 'Nehwon', power: 'Favors thief gods and luck deities' },
  // Celtic shards
  { name: 'Cauldron\'s Chip', origin: 'The Dagda\'s cauldron fed armies and never emptied. Once, a single chip fell from its rim. That chip became this shard. It remembers what it means to be whole.', color: '#c0a060', glow: 'rgba(180,150,80,.6)', pantheon: 'Celtic', power: 'Favors Celtic Tuatha Dé Danann' },
  { name: 'Stone of Destiny\'s Splinter', origin: 'The Lia Fáil screams when a true king touches it. This shard fell from it during one such scream. It has been silent ever since, waiting for the right hand.', color: '#a0a0b0', glow: 'rgba(150,150,170,.6)', pantheon: 'Celtic', power: 'Favors lawful Celtic gods' },
  // Other pantheons
  { name: 'Tenth Avatar\'s Tear', origin: 'When Kalki, the final avatar of Vishnu, shall end the world, a single tear will fall. This shard is that tear, fallen backward through time. It knows how everything ends.', color: '#b06060', glow: 'rgba(170,80,80,.6)', pantheon: 'Indian', power: 'Favors Indian pantheon, Trimurti' },
  { name: 'Jade Emperor\'s Reflection', origin: 'In the Heavenly Court, the Jade Emperor gazed into a mirror of starlight. His reflection stepped out and became this shard. It thinks it is the Emperor. It might be right.', color: '#70a070', glow: 'rgba(90,150,90,.6)', pantheon: 'Chinese', power: 'Favors Chinese Celestial Bureaucracy' },
  { name: 'Amaterasu\'s Hidden Spark', origin: 'When Amaterasu hid in a cave, the world went dark. But one spark of her light escaped and became this shard. It has been looking for her ever since.', color: '#f0e0a0', glow: 'rgba(240,210,140,.6)', pantheon: 'Japanese', power: 'Favors Japanese kami, solar deities' },
  { name: 'Quetzalcoatl\'s Shed Scale', origin: 'The Feathered Serpent sheds his skin once an age. This scale fell from that shedding, still warm, still golden, still remembering what it meant to be part of a god.', color: '#d0c060', glow: 'rgba(200,180,80,.6)', pantheon: 'Central American', power: 'Favors Aztec/Mayan pantheon, good-aligned gods' },
  { name: 'Marduk\'s Tablet Shard', origin: 'When Marduk wrote the laws of heaven on tablets of lapis lazuli, one tablet cracked. This shard holds those lost laws—commandments that were never spoken, rules that were never obeyed.', color: '#3040a0', glow: 'rgba(40,50,150,.6)', pantheon: 'Babylonian', power: 'Favors Babylonian pantheon, lawful gods' },

  // ═══════════════════════════════════════════════════════════════════════════
  // KRYNN (DRAGONLANCE) SHARDS - Artifacts from the world of Krynn
  // ═══════════════════════════════════════════════════════════════════════════
  { name: 'Graygem Fragment', origin: 'When Reorx forged the Graygem to capture Chaos, a single fragment broke free. It has been passing through hands ever since—kings, thieves, gods, and fools. Each holder believes they understand it. None have. The Graygem Fragment contains the essence of Chaos itself, and it does not grant power—it grants possibility. The wrong kind of possibility.', color: '#808080', glow: 'rgba(128,128,128,.6)', pantheon: 'Krynn', power: 'Favors Krynn pantheon, chaotic outcomes, wild magic' },
  { name: 'Blue Crystal Splinter', origin: 'Mishakal\'s Blue Crystal Staff was not always whole. It was forged from fragments, and one fragment was lost during the Cataclysm. This splinter remembers what it means to bring the gods back. It aches for the faith that once made it whole. It will grant healing to any who touch it, but it demands belief in return.', color: '#4080c0', glow: 'rgba(64,128,192,.6)', pantheon: 'Krynn', power: 'Favors Mishakal, healing, good-aligned gods of Krynn' },
  { name: 'Dragonlance Shard', origin: 'Huma Dragonbane rode into legend with a lance forged by the god Reorx himself. When he struck down Takhisis\'s champion, a splinter broke from the lance. It has been found in dragon hoards across Krynn, never staying long in one place. Dragons fear it. Dragonlords seek it. It remembers the death of a god\'s champion.', color: '#c0a040', glow: 'rgba(192,160,64,.6)', pantheon: 'Krynn', power: 'Favors Paladine, Huma\'s legacy, dragon-slaying' },
  { name: 'Blood of the Conclave', origin: 'When the Towers of High Sorcery fell, the Conclave of Wizards preserved a single crystallized drop of blood—mixed from all three Orders. It contains the essence of White, Red, and Black magic equally. It does not favor any order. It demands balance. The shard whispers to mages in their sleep, offering power at the cost of their alignment.', color: '#a02020', glow: 'rgba(160,32,32,.6)', pantheon: 'Krynn', power: 'Favors Solinari, Lunitari, Nuitari equally - demands balance' },
  { name: 'Takhisis\'s Broken Crown', origin: 'When the Dark Queen was cast out of Krynn, a piece of her crown fell to the world below. It has been seeking her ever since. Those who hold it hear her voice—sometimes a whisper, sometimes a scream. It offers dominion over shadows and the loyalty of dark things. It asks only for devotion. Total devotion.', color: '#200020', glow: 'rgba(32,0,32,.8)', pantheon: 'Krynn', power: 'Favors Takhisis, evil dragons, shadow magic' },
  { name: 'Knighthood\'s Honor', origin: 'The Knights of Solamnia measure honor in oaths kept and deeds done. When the first Knight of the Rose fell in battle, his crystallized honor became this shard. It weighs heavily in the hands of those who hold it—lighter for the honorable, heavier for the corrupt. It can show the truth of any knight\'s soul. Some cannot bear to hold it.', color: '#d4af37', glow: 'rgba(212,175,55,.6)', pantheon: 'Krynn', power: 'Favors Paladine, Kiri-Jolith, Solamnic Knights' },
  { name: 'Kender\'s Curiosity', origin: 'Tasslehoff Burrfoot once touched something he should not have. His curiosity was so pure, so absolute, that it crystallized into this shard. It has been turning up in pockets ever since. The shard grants luck beyond reason—but it also attracts the attention of things that should not be noticed. Things that notice back.', color: '#ff8040', glow: 'rgba(255,128,64,.6)', pantheon: 'Krynn', power: 'Favors Branchala, kender luck, chaos (benign)' },
  { name: 'Tower of Wayreth\'s Key', origin: 'The Tower of High Sorcery at Wayreth moves through time and space. It has doors that open to every plane. One key broke off in a lock long ago and became this shard. It can open any door—physical, planar, or metaphorical. But what opens can also close, and the Tower does not appreciate keys that fall into the wrong hands.', color: '#604080', glow: 'rgba(96,64,128,.6)', pantheon: 'Krynn', power: 'Favors the Conclave, planar travel, unlocking secrets' },
  { name: 'Fistandantilus\'s Last Memory', origin: 'When Raistlin Majere consumed the archmage Fistandantilus, one memory escaped—a single moment of the ancient wizard\'s existence that refused to be absorbed. This shard contains that memory. It whispers secrets of immortality, of survival at any cost. It knows things that even gods have forgotten. It is patient. It is waiting.', color: '#400020', glow: 'rgba(64,0,32,.8)', pantheon: 'Krynn', power: 'Favors dark magic, undead, those who seek forbidden knowledge' }
]

// ═══════════════════════════════════════════════════════════════════════════
// INJURY SYSTEM - Physical, Magic, Poison, Psionic damage types (AD&D 1e)
// ═══════════════════════════════════════════════════════════════════════════

export const INJURY_TABLE: Omit<Injury, 'turnsLeft'>[] = [
  // === PHYSICAL INJURIES (from weapons, falls, impacts) ===
  { id: 'deep_cut', name: 'Deep Cut', effect: '-1 to all attack rolls', modifier: { attack: -1 }, icon: '🩸', type: 'physical', cure: 'Rest 2 turns or Cure Light Wounds' },
  { id: 'bruised_ribs', name: 'Bruised Ribs', effect: '-2 to DEX saves and movement', modifier: { dex_save: -2 }, icon: '💔', type: 'physical', cure: 'Rest 3 turns' },
  { id: 'concussion', name: 'Concussion', effect: '-4 to INT checks, -1 to all saves', modifier: { int_check: -4, save: -1 }, icon: '💫', type: 'physical', cure: 'Rest 5 turns or Cure Light Wounds' },
  { id: 'crushed_hand', name: 'Crushed Hand', effect: '-2 to attack rolls, cannot use two-handed weapons', modifier: { attack: -2 }, icon: '✊', type: 'physical', cure: 'Cure Serious Wounds or Rest 10 turns' },
  { id: 'broken_limb', name: 'Broken Limb', effect: 'Cannot use one arm/leg, -4 AC', modifier: { ac: -4 }, icon: '🦴', type: 'physical', cure: 'Cure Serious Wounds or week of rest' },
  { id: 'internal_bleeding', name: 'Internal Bleeding', effect: '-3 HP at start of each turn', modifier: { dot: -3 }, icon: '💧', type: 'physical', cure: 'Cure Serious Wounds' },
  { id: 'lacerated_eye', name: 'Lacerated Eye', effect: '-4 to ranged attacks, -2 perception', modifier: { ranged: -4 }, icon: '👁️', type: 'physical', cure: 'Cure Serious Wounds' },
  { id: 'severed_tendon', name: 'Severed Tendon', effect: 'Movement halved, -3 DEX', modifier: { dex: -3, movement: -0.5 }, icon: '🔧', type: 'physical', cure: 'Cure Critical Wounds or Regenerate' },
  
  // === MAGICAL INJURIES (from spells, magical attacks) ===
  { id: 'arcane_burn', name: 'Arcane Burn', effect: '-2 to saves vs magic, spells cast at -1 level', modifier: { magic_save: -2 }, icon: '🔥', type: 'magic', cure: 'Dispel Magic + Cure Light Wounds' },
  { id: 'soul_fracture', name: 'Soul Fracture', effect: '-3 to all saves vs death, cannot be raised if slain', modifier: { death_save: -3 }, icon: '👻', type: 'magic', cure: 'Restoration spell' },
  { id: 'planar_taint', name: 'Planar Taint', effect: 'Save at -2 each turn or lose 1 WIS', modifier: { wis_save: -2 }, icon: '🌀', type: 'magic', cure: 'Remove Curse + Cure Disease' },
  { id: 'mana_drain', name: 'Mana Drain', effect: 'Cannot cast spells above 3rd level, -2 INT', modifier: { int: -2 }, icon: '💠', type: 'magic', cure: 'Rest 8 hours or Restoration' },
  { id: 'eldritch_corrosion', name: 'Eldritch Corrosion', effect: 'Magical items held lose 1 charge per turn', modifier: { item_drain: -1 }, icon: '⚗️', type: 'magic', cure: 'Mending + Dispel Evil' },
  { id: 'spellscar', name: 'Spellscar', effect: 'Random spell fails each combat, -1 caster level', modifier: { caster_level: -1 }, icon: '⚡', type: 'magic', cure: 'Limited Wish or higher' },
  
  // === POISON INJURIES (from toxins, venomous creatures) ===
  { id: 'weak_poison', name: 'Weak Poison', effect: '-1 to all rolls, -2 HP/turn for 4 turns', modifier: { all_rolls: -1, dot: -2 }, icon: '🤢', type: 'poison', cure: 'Antitoxin or Neutralize Poison' },
  { id: 'necrotic_venom', name: 'Necrotic Venom', effect: '-2 CON permanently, -3 HP/turn', modifier: { con: -2, dot: -3 }, icon: '☠️', type: 'poison', cure: 'Neutralize Poison + Restoration' },
  { id: 'paralytic_toxin', name: 'Paralytic Toxin', effect: 'DEX halved, 20% chance paralyzed each turn', modifier: { dex_mult: 0.5 }, icon: '🕸️', type: 'poison', cure: 'Neutralize Poison or Antitoxin' },
  { id: 'blood_toxin', name: 'Blood Toxin', effect: 'Cannot be healed by magic, regen halved', modifier: { healing_mult: 0 }, icon: '🧫', type: 'poison', cure: 'Neutralize Poison' },
  { id: 'mind_poison', name: 'Mind Poison', effect: '-3 WIS, -3 INT, save each turn or confused', modifier: { wis: -3, int: -3 }, icon: '🧠', type: 'poison', cure: 'Neutralize Poison + Heal' },
  { id: 'acid_burn', name: 'Acid Burn', effect: '-2 AC, -1 to saves, -1 HP/turn per acid wound', modifier: { ac: -2, save: -1 }, icon: '🧪', type: 'poison', cure: 'Neutralize Poison or water flush' },
  
  // === PSIONIC INJURIES (from mental attacks, AD&D 1e psionics) ===
  { id: 'mental_fatigue', name: 'Mental Fatigue', effect: '-2 to INT/WIS checks, psionic power halved', modifier: { int: -2, wis: -2 }, icon: '😣', type: 'psionic', cure: 'Rest 8 hours' },
  { id: 'psychic_trauma', name: 'Psychic Trauma', effect: 'Random phobia developed, -3 to CHA', modifier: { cha: -3 }, icon: '😰', type: 'psionic', cure: 'Heal or Cure Insanity' },
  { id: 'mind_bleed', name: 'Mind Bleed', effect: '-1 to all saves, 10% spell failure', modifier: { save: -1 }, icon: '💭', type: 'psionic', cure: 'Restoration or Psychic Surgery' },
  { id: 'ego_fracture', name: 'Ego Fracture', effect: 'CHA halved, cannot use psionics, -2 leadership', modifier: { cha_mult: 0.5 }, icon: '🎭', type: 'psionic', cure: 'Heal + Restoration' },
  { id: 'thought_burn', name: 'Thought Burn', effect: 'Cannot memorize new spells, -4 INT saves', modifier: { int_save: -4 }, icon: '💥', type: 'psionic', cure: 'Restoration or Psychic Surgery' },
  { id: 'psionic_shock', name: 'Psionic Shock', effect: 'Stunned 1d4 rounds on failed save, -3 WIS', modifier: { wis: -3 }, icon: '💫', type: 'psionic', cure: 'Heal or 24 hours rest' },
  
  // === CURSED/SPECIAL INJURIES ===
  { id: 'cursed_wound', name: 'Cursed Wound', effect: 'Cannot be healed by magic, -3 to saves vs death', modifier: { death_save: -3 }, icon: '🌑', type: 'magic', cure: 'Remove Curse first, then healing' },
  { id: 'divine_mark', name: 'Divine Mark', effect: 'Marked by a god, -2 to saves vs that god\'s domain', modifier: { domain_save: -2 }, icon: '✝️', type: 'magic', cure: 'Atonement or divine intervention' }
]

// ═══════════════════════════════════════════════════════════════════════════
// ITEM SYSTEM - Acquisition through encounters, battle, conversation, pickpocket
// ═══════════════════════════════════════════════════════════════════════════

export const ITEM_TEMPLATES: Item[] = [
  // === POTIONS (Mostly from exploration, quest rewards, NPC encounters) ===
  { id: 'healing_potion', name: 'Healing Potion', type: 'potion', rarity: 'common', effect: 'Restore 2d8+4 HP', modifier: { healing: 20 }, charges: 1, maxCharges: 1, icon: '🧪', description: 'A crimson liquid that glimmers with restorative magic.', acquisition: ['npc_encounter', 'monster_drop', 'exploration', 'pickpocket'], source: 'Any', value: 50 },
  { id: 'greater_healing', name: 'Greater Healing Potion', type: 'potion', rarity: 'uncommon', effect: 'Restore 4d8+8 HP', modifier: { healing: 40 }, charges: 1, maxCharges: 1, icon: '💜', description: 'A potent healing draught used by legendary heroes.', acquisition: ['npc_encounter', 'monster_drop', 'quest_reward'], source: 'Lesser gods, Heroes', value: 200 },
  { id: 'heroism_elixir', name: 'Elixir of Heroism', type: 'potion', rarity: 'rare', effect: 'Gain +2 to all saves for 10 turns', modifier: { all_saves: 2 }, charges: 1, maxCharges: 1, icon: '✨', description: 'Liquid courage distilled from the essence of fallen champions.', acquisition: ['quest_reward', 'npc_encounter'], source: 'Greater gods, Heroes', value: 1000 },
  { id: 'ambrosia', name: 'Ambrosia', type: 'potion', rarity: 'legendary', effect: 'Restore to full HP, cure all injuries', modifier: { full_heal: 1 }, charges: 1, maxCharges: 1, icon: '🍯', description: 'Food of the gods. A single drop can restore mortal flesh.', acquisition: ['npc_encounter', 'quest_reward'], source: 'Greek gods only', value: 5000 },
  { id: 'antitoxin', name: 'Antitoxin', type: 'potion', rarity: 'common', effect: 'Cure poison injuries', modifier: { cure_poison: 1 }, charges: 1, maxCharges: 1, icon: '💚', description: 'A bitter green paste that neutralizes most poisons.', acquisition: ['npc_encounter', 'exploration', 'pickpocket'], source: 'Any', value: 75 },
  { id: 'neutralize_poison', name: 'Universal Antidote', type: 'potion', rarity: 'uncommon', effect: 'Cure all poison and psionic injuries', modifier: { cure_all_poison: 1 }, charges: 1, maxCharges: 1, icon: '💠', description: 'A shimmering liquid that purifies body and mind.', acquisition: ['quest_reward', 'npc_encounter'], source: 'Lawful gods', value: 500 },
  { id: 'potion_giant_strength', name: 'Potion of Giant Strength', type: 'potion', rarity: 'rare', effect: 'STR becomes 18/00 for 1 hour', modifier: { str_set: 18 }, charges: 1, maxCharges: 1, icon: '💪', description: 'Your muscles surge with titanic power.', acquisition: ['monster_drop', 'quest_reward', 'exploration'], source: 'Giants, Norse gods', value: 800 },
  { id: 'potion_invisibility', name: 'Potion of Invisibility', type: 'potion', rarity: 'rare', effect: 'Become invisible for 1 hour or until attacking', modifier: { invisible: 1 }, charges: 1, maxCharges: 1, icon: '👁️', description: 'You fade from sight. The glass seems to hold nothing.', acquisition: ['pickpocket', 'quest_reward', 'exploration'], source: 'Trickster gods, Rogues', value: 1000 },
  
  // === ARTIFACTS (From gods, legendary encounters, quest rewards) ===
  { id: 'mysterious_key', name: 'Mysterious Key', type: 'artifact', rarity: 'rare', effect: 'Opens unknown doors', charges: 3, maxCharges: 3, icon: '🗝️', description: 'An ancient key that hums with potential. What lock does it fit?', acquisition: ['exploration', 'pickpocket', 'conversation'], source: 'Any dungeon', value: 500 },
  { id: 'divine_shield', name: 'Aegis Fragment', type: 'artifact', rarity: 'legendary', effect: 'Absorb next lethal blow once', modifier: { death_ward: 1 }, charges: 1, maxCharges: 1, icon: '🛡️', description: 'A splinter of Athena\'s shield, still radiating protective magic.', acquisition: ['npc_encounter', 'quest_reward'], source: 'Greek gods', value: 10000 },
  { id: 'thunder_hammer', name: 'Hammer of Storms', type: 'equipment', rarity: 'legendary', effect: '+15 damage, stuns on crit', modifier: { damage: 15 }, charges: 99, maxCharges: 99, icon: '🔨', description: 'Forged by Hephaestus, claimed by Thor, lost to time.', acquisition: ['monster_drop', 'quest_reward'], source: 'Norse gods, Giants', value: 15000 },
  { id: 'golden_fleece', name: 'Golden Fleece', type: 'artifact', rarity: 'legendary', effect: 'Heal 2d8 HP per turn, immune to fear', modifier: { regen: 8, fear_immune: 1 }, charges: 99, maxCharges: 99, icon: '🐏', description: 'The legendary fleece of the ram that saved Phrixus and Helle.', acquisition: ['quest_reward', 'exploration'], source: 'Greek pantheon', value: 20000 },
  { id: 'runestaff', name: 'Odin\'s Runestaff', type: 'artifact', rarity: 'legendary', effect: 'Cast any 1st-3rd level spell once per day', modifier: { spell_cast: 1 }, charges: 99, maxCharges: 99, icon: '🔱', description: 'Carved with runes of power, this staff whispers secrets.', acquisition: ['npc_encounter', 'quest_reward'], source: 'Norse gods', value: 12000 },
  { id: 'eye_horus', name: 'Eye of Horus', type: 'artifact', rarity: 'legendary', effect: 'See invisible, immune to illusions', modifier: { true_sight: 1 }, charges: 99, maxCharges: 99, icon: '👁️', description: 'The recovered eye of Horus, torn out and returned, sees all.', acquisition: ['quest_reward', 'monster_drop'], source: 'Egyptian gods', value: 8000 },
  { id: 'stormbringer_shard', name: 'Stormbringer Shard', type: 'artifact', rarity: 'legendary', effect: '+20 damage, steals 1d6 HP per hit', modifier: { damage: 20, vampiric: 6 }, charges: 99, maxCharges: 99, icon: '⚔️', description: 'A fragment of the Black Sword. It whispers of souls.', acquisition: ['quest_reward'], source: 'Melnibonéan only', value: 25000 },
  { id: 'necklace_bracelets', name: 'Bracelets of Submission', type: 'artifact', rarity: 'rare', effect: 'Charisma +4, Dominate Person 1/day', modifier: { cha: 4 }, charges: 99, maxCharges: 99, icon: '📿', description: 'Golden bracelets worn by those who command absolute loyalty.', acquisition: ['pickpocket', 'conversation', 'quest_reward'], source: 'Egyptian pantheon', value: 3000 },
  
  // === EQUIPMENT (From battle, monster drops, NPC encounters) ===
  { id: 'mithral_chain', name: 'Mithral Chain', type: 'equipment', rarity: 'rare', effect: 'AC -2, no DEX penalty, weightless', modifier: { ac: -2 }, charges: 99, maxCharges: 99, icon: '⛓️', description: 'Links of silver-white metal, light as silk, hard as dragon scales.', acquisition: ['monster_drop', 'npc_encounter', 'quest_reward'], source: 'Dwarves, Elves', value: 2000 },
  { id: 'flame_blade', name: 'Flame Blade', type: 'equipment', rarity: 'uncommon', effect: '+5 fire damage, illuminates 30ft', modifier: { damage: 5, fire: 1 }, charges: 99, maxCharges: 99, icon: '🗡️', description: 'A blade that burns with eternal flame.', acquisition: ['monster_drop', 'exploration', 'battle'], source: 'Fire creatures, Fire gods', value: 800 },
  { id: 'frost_brand', name: 'Frost Brand', type: 'equipment', rarity: 'rare', effect: '+8 cold damage, extinguishes fires', modifier: { damage: 8, cold: 1 }, charges: 99, maxCharges: 99, icon: '❄️', description: 'A sword of eternal winter, cold enough to freeze flame.', acquisition: ['monster_drop', 'quest_reward'], source: 'Ice creatures, Norse gods', value: 1500 },
  { id: 'vorpal_blade', name: 'Vorpal Blade', type: 'equipment', rarity: 'legendary', effect: 'Natural 20 beheads instantly, +10 damage', modifier: { damage: 10, vorpal: 1 }, charges: 99, maxCharges: 99, icon: '⚔️', description: 'A blade that seeks necks. It never dulls.', acquisition: ['quest_reward'], source: 'Fate, Death gods', value: 30000 },
  { id: 'boots_speed', name: 'Boots of Speed', type: 'equipment', rarity: 'rare', effect: 'Double movement, +2 AC', modifier: { movement: 2, ac: -2 }, charges: 99, maxCharges: 99, icon: '👢', description: 'Seven-league boots that make the world feel small.', acquisition: ['pickpocket', 'exploration', 'quest_reward'], source: 'Trickster gods', value: 2500 },
  { id: 'cloak_displacement', name: 'Cloak of Displacement', type: 'equipment', rarity: 'uncommon', effect: 'First attack each combat auto-misses, +2 AC', modifier: { ac: -2, displacement: 1 }, charges: 99, maxCharges: 99, icon: '🧥', description: 'You appear to be three feet from where you actually stand.', acquisition: ['monster_drop', 'pickpocket', 'exploration'], source: 'Illusionists, Monsters', value: 1000 },
  
  // === SCROLLS (From exploration, NPC encounters, conversation) ===
  { id: 'scroll_wisdom', name: 'Scroll of Divine Wisdom', type: 'scroll', rarity: 'uncommon', effect: 'Reveal hidden truths about one entity', charges: 1, maxCharges: 1, icon: '📜', description: 'The ink shifts and rearranges itself, always revealing what you need to know.', acquisition: ['exploration', 'npc_encounter', 'conversation'], source: 'Any', value: 300 },
  { id: 'scroll_protection', name: 'Scroll of Protection from Evil', type: 'scroll', rarity: 'uncommon', effect: '-2 to enemy saves, +2 to saves vs evil', modifier: { protection: 2 }, charges: 1, maxCharges: 1, icon: '📄', description: 'A barrier of holy light surrounds the reader.', acquisition: ['exploration', 'quest_reward', 'conversation'], source: 'Lawful good gods', value: 400 },
  { id: 'scroll_undead', name: 'Scroll of Protection from Undead', type: 'scroll', rarity: 'rare', effect: 'Undead cannot approach within 10ft', modifier: { undead_ward: 1 }, charges: 1, maxCharges: 1, icon: '💀', description: 'A scroll inscribed with forbidden names of the dead.', acquisition: ['exploration', 'monster_drop'], source: 'Undead, Necromancers', value: 600 },
  { id: 'scroll_summon', name: 'Scroll of Summoning', type: 'scroll', rarity: 'rare', effect: 'Summon one ally from the pantheon of your shard', charges: 1, maxCharges: 1, icon: '📑', description: 'Names of power that can call across the boundaries.', acquisition: ['quest_reward', 'npc_encounter'], source: 'Any god', value: 1500 },
  { id: 'scroll_identify', name: 'Scroll of Identification', type: 'scroll', rarity: 'common', effect: 'Identify all properties of one item', charges: 1, maxCharges: 1, icon: '📋', description: 'The true nature of things becomes clear.', acquisition: ['npc_encounter', 'exploration', 'pickpocket'], source: 'Any', value: 100 },
  { id: 'scroll_teleport', name: 'Scroll of Teleportation', type: 'scroll', rarity: 'rare', effect: 'Teleport party to known location', charges: 1, maxCharges: 1, icon: '🌀', description: 'Distance is meaningless. Fold the world and step through.', acquisition: ['quest_reward', 'pickpocket'], source: 'Magic gods, Tricksters', value: 1000 },
  
  // === SPECIAL ITEMS (Unique acquisition methods) ===
  { id: 'thieves_tools', name: 'Master Thieves\' Tools', type: 'equipment', rarity: 'uncommon', effect: '+2 to pickpocket and lockpicking', modifier: { thievery: 2 }, charges: 99, maxCharges: 99, icon: '🔧', description: 'The tools of a master thief. Nothing stays locked for long.', acquisition: ['pickpocket', 'conversation'], source: 'Rogues, Thieves Guild', value: 500 },
  { id: 'diplomats_ring', name: 'Diplomat\'s Ring', type: 'artifact', rarity: 'uncommon', effect: '+3 to persuasion, detect lies', modifier: { persuasion: 3, detect_lies: 1 }, charges: 99, maxCharges: 99, icon: '💍', description: 'A gift from the gods of commerce and speech.', acquisition: ['conversation', 'quest_reward', 'npc_encounter'], source: 'Lawful gods, Trade gods', value: 600 },
  { id: 'monster_lore_book', name: 'Monster Lore Compendium', type: 'artifact', rarity: 'rare', effect: 'Reveal one weakness of any monster encountered', modifier: { lore: 1 }, charges: 99, maxCharges: 99, icon: '📖', description: 'Centuries of monster-hunting wisdom, bound in leather.', acquisition: ['exploration', 'conversation', 'pickpocket'], source: 'Scholars, Sages', value: 800 },
  { id: 'bag_holding', name: 'Bag of Holding', type: 'artifact', rarity: 'rare', effect: 'Carry 500 lbs without weight', modifier: { capacity: 500 }, charges: 99, maxCharges: 99, icon: '👜', description: 'A bag that opens into a pocket dimension.', acquisition: ['pickpocket', 'quest_reward', 'exploration'], source: 'Magic users', value: 2000 },
  { id: 'luckstone', name: 'Stone of Good Luck', type: 'artifact', rarity: 'uncommon', effect: '+1 to all saves', modifier: { save: 1 }, charges: 99, maxCharges: 99, icon: '🍀', description: 'A smooth stone that seems to roll toward fortune.', acquisition: ['exploration', 'pickpocket', 'battle'], source: 'Any', value: 400 },
  { id: 'blessed_cloak', name: 'Blessed Cloak', type: 'equipment', rarity: 'uncommon', effect: '+1 AC, +2 to saves vs evil', modifier: { ac: -1, evil_save: 2 }, charges: 99, maxCharges: 99, icon: '🧣', description: 'Woven by priestesses and blessed by the gods.', acquisition: ['npc_encounter', 'quest_reward', 'conversation'], source: 'Good-aligned gods', value: 500 }
]

export const NPC_NAMES: { [key: string]: string[] } = {
  greater_gods: ['zeus', 'odin', 'set', 'loki', 'ares', 'cthulhu', 'hel', 'tezcatlipoca', 'osiris', 'indra', 'vishnu', 'shiva', 'quetzalcoatl', 'ra', 'isis', 'ptah', 'thoth', 'marduk', 'dagda', 'lugh', 'tlaloc', 'rudra', 'freya', 'thor', 'tyr', 'balder', 'hera', 'poseidon', 'hades', 'apollo', 'athena', 'hermes', 'aphrodite', 'amaterasu', 'izanagi', 'gruumsh', 'moradin', 'corellon', 'kos', 'death_nehwon', 'silvanus'],
  lesser_gods: ['anubis', 'bast', 'artemis', 'pan', 'demeter', 'hephaestus', 'dionysus', 'nike', 'bragi', 'aegir', 'surtur', 'thrym', 'nyarlathotep', 'shub_niggurath', 'kali', 'lakshmi', 'ramman', 'nergal', 'druaga', 'girru', 'nin_hursag', 'morrigan', 'brigit', 'goibhnie', 'diancecht', 'tou_mu', 'lu_yueh', 'huan_ti', 'tobadzistsini', 'coyote', 'raven', 'mielikki', 'ilmatar', 'untamo', 'huitzilopochtli', 'arioch', 'rat_god', 'sekolah', 'lolth', 'susanowo', 'mishakal', 'reorx', 'gilean', 'branchala', 'chemosh', 'zeboim', 'sirrion', 'habbakuk', 'sargonnas'],
  heroes: ['arthur', 'galahad', 'lancelot', 'gawaine', 'tristram', 'merlin', 'morgan_le_fay', 'lamorak', 'gareth', 'palomides', 'pellinore', 'gilgamesh', 'cuchulainn', 'heracles_hero', 'perseus', 'odysseus', 'jason', 'theseus', 'bellerophon', 'vainamoinen', 'ilmarinen', 'lemminkainen', 'kullervo', 'elric', 'moonglum', 'fafhrd', 'gray_mouser', 'movarl', 'raiko', 'yamamoto_date', 'yoshmye', 'hunapu', 'qagwaaz', 'hiawatha', 'stoneribs', 'tanis_half_elven', 'sturm_brightblade', 'raistlin_majere_hero', 'caramon_majere', 'goldmoon', 'riverwind', 'laurana', 'kitiara_uth_matar', 'flint_fireforge', 'tasslehoff_burrfoot', 'tika_waylan', 'gilthanas', 'derek_crownguard'],
  demigods: ['karttikeya', 'yama', 'ratri', 'tvashtri', 'oh_kuni_nushi', 'hachiman', 'surma', 'loviatar', 'kiputytto', 'aarth', 'issek_of_jug', 'spider_god', 'votishal', 'gods_of_lankhmar', 'apshai', 'ithaqua', 'chao_kung_ming', 'chih_chiang_fyu_ya', 'no_cha', 'wen_chung', 'fei_lien', 'fileet', 'haaashastaak', 'meerclar', 'nnuuurrrrc', 'vaprak', 'laogzed', 'fizban', 'cyan_bloodbane', 'lord_soth', 'huma_dragonbane', 'fistandantilus', 'raistlin_majere_demigod'],
  monsters: ['fenris', 'jormungandr', 'cerberus', 'apep', 'shoggoth', 'mi_go', 'byakhee', 'deep_ones', 'primordial_one', 'thunder_bird', 'blodug_hofi', 'ma_yuan', 'malystryx', 'khellendros', 'shadow_wights', 'draconians']
}

// ═══════════════════════════════════════════════════════════════════════════
// GREATER GODS - Possible antagonists (identity revealed in Act III)
// ═══════════════════════════════════════════════════════════════════════════

export const ALL_GREATER_GODS = [
  // ═══════════════════════════════════════════════════════════════════════════
  // GREEK PANTHEON - 9 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'zeus', name: 'Zeus', title: 'Lord of Olympus', pantheon: 'Greek', align: 'Chaotic neutral', hp: 400, AC: -5, MR: 95, phase1: 'Lightning bolt barrage — 100 dice/day. Shape change at will. No female can resist him.', phase2: 'Summons 1d10 titans. Divine storm 500yd radius, all saves at -2. Commands all Olympian gods.', phase3: 'TRUE FORM: sky darkens, 3 bolts/round + divine storm, all saves at -4. King of gods unleashed.', personality: 'Arrogant, lustful, ultimately just. Deeply insulted by any challenge. Commands absolute respect.', domain: 'sky, thunder, kingship', symbol: 'lightning bolt, eagle, bull' },
  { id: 'hera', name: 'Hera', title: 'Queen of the Gods', pantheon: 'Greek', align: 'Neutral', hp: 300, AC: 2, MR: 50, phase1: 'Voice: 20 pts damage to all within 50 yards when angry (no save). Spy network knows all in her domain.', phase2: 'Peacock throne: immune to surprise. Queens authority: commands respect from all gods.', phase3: 'WRATH OF THE QUEEN: all who have wronged her suffer. Divine curses irreversible.', personality: 'Proud, jealous, politically masterful. Hell to cross. Never forgets a slight.', domain: 'marriage, women, sovereignty', symbol: 'peacock, cow, pomegranate, diadem' },
  { id: 'athena', name: 'Athena', title: 'Goddess of Wisdom', pantheon: 'Greek', align: 'Lawful good', hp: 329, AC: -2, MR: 80, phase1: 'Petrification gaze never misses. Anti-magic shell. 20th fighter/cleric.', phase2: 'Wisdom gift: permanently +1 WIS to those she blesses. Strategic mastery reveals enemy weaknesses.', phase3: 'GODDESS OF WAR: tactical omniscience. All allies +4 to hit. No enemy can surprise her.', personality: 'Precise, patient, strategic. Hates Ares absolutely. Favors the clever over the strong.', domain: 'wisdom, war, crafts, justice', symbol: 'owl, olive tree, aegis, spear' },
  { id: 'ares', name: 'Ares', title: 'God of War', pantheon: 'Greek', align: 'Chaotic evil', hp: 333, AC: -2, MR: 59, phase1: 'Anti-magic shell. Blink ability: teleport 60ft. Invulnerable to poison/petrification on Prime Material.', phase2: 'Summons army of 100 immortal warriors. Blood frenzy grants double attacks. All combat rolls +5.', phase3: 'WAR INCARNATE: All violence empowers him. Cannot be harmed by weapons. Hates Athena with divine hatred.', personality: 'Brutal, simple, magnificent. Respects bleeding. Cowardly when losing. Glories in slaughter.', domain: 'war, violence, courage', symbol: 'spear, helmet, vultures, dog' },
  { id: 'apollo', name: 'Apollo', title: 'God of Light and Truth', pantheon: 'Greek', align: 'Neutral good', hp: 390, AC: -2, MR: 70, phase1: 'Bow +4: never misses at any line-of-sight distance. Disintegrate 1/round. Sun chariot: travel any plane.', phase2: 'Prophecy: always accurate (always cryptic). Light aura blinds undead. Music: all who hear are enchanted.', phase3: 'SUN GOD ASCENDANT: Light burns all darkness. No lies can be spoken. Future and present become one.', personality: 'Beautiful, distant, tells the future badly on purpose. God of light, truth, and music.', domain: 'light, truth, prophecy, music, healing', symbol: 'lyre, laurel, sun chariot, raven' },
  { id: 'poseidon', name: 'Poseidon', title: 'Earth-Shaker', pantheon: 'Greek', align: 'Chaotic neutral', hp: 390, AC: 3, MR: 75, phase1: 'Trident +5: absorbs any spell. Earthquake at will. Controls all sea creatures.', phase2: 'Tsunami: 200ft wave 1/day. All within 1 mile save vs death or drown. Swim unlimited.', phase3: 'THE SEA ITSELF RISES: battlefield becomes ocean, drowning inevitable. Trident commands waves.', personality: 'Proud, unpredictable, enormous. The ocean has his moods. Holds grudges for generations.', domain: 'sea, earthquakes, horses', symbol: 'trident, dolphin, horse, bull' },
  { id: 'hades', name: 'Hades', title: 'Lord of the Underworld', pantheon: 'Greek', align: 'Lawful evil', hp: 400, AC: -4, MR: 80, phase1: 'Helm of invisibility at will. Commands all Greek dead. Death touch 3/day: save at -4 or die.', phase2: 'River Styx flows. All deaths permanent without divine intervention. Never releases souls willingly.', phase3: 'KING OF THE DEAD: All slain rise as his servants. No escape from his domain. Rules the inevitable.', personality: 'Cold, calculating, patient. Does not forget debts. All souls belong to him eventually.', domain: 'underworld, death, wealth', symbol: 'helm of darkness, bident, pomegranate, keys' },
  { id: 'hermes', name: 'Hermes', title: 'Messenger of the Gods', pantheon: 'Greek', align: 'Neutral', hp: 340, AC: 2, MR: 35, phase1: 'Always hasted. Caduceus: controls all non-magical creatures. 25th thief skills.', phase2: 'Messenger: teleport between any planes instantly. Knows all paths, all doors, all secrets of travel.', phase3: 'GOD OF SPEED: moves faster than thought. Can deliver messages through time itself. No distance exists.', personality: 'Quick, clever, amoral by divine necessity. Helps everyone a little. Patron of thieves and travelers.', domain: 'travel, commerce, thieves, messengers', symbol: 'caduceus, winged sandals, winged helmet' },
  { id: 'aphrodite', name: 'Aphrodite', title: 'Goddess of Love', pantheon: 'Greek', align: 'Neutral good', hp: 350, AC: 0, MR: 60, phase1: 'Any being looking at her: save vs. spells or permanently infatuated. Detects love and attraction in any being.', phase2: 'Love magic: enchant any target. Beauty aura: +6 CHA to any she blesses. No heart is closed to her.', phase3: 'GODDESS OF DESIRE: Love causes more wars than Ares. All who fight for her fight to the death.', personality: 'Not as shallow as she seems. Love is her weapon and her wound. Generous and terrible in equal measure.', domain: 'love, beauty, desire', symbol: 'dove, rose, swan, myrtle' },

  // ═══════════════════════════════════════════════════════════════════════════
  // NORSE PANTHEON - 7 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'odin', name: 'Odin', title: 'All-Father', pantheon: 'Norse', align: 'Neutral good', hp: 400, AC: -6, MR: 85, phase1: 'Gungnir never misses, returns to hand. Huginn and Muninn reveal all secrets. Paralysis gaze.', phase2: 'Summons Valkyries. Can cast any spell. Rune magic devastating. Berserker blessing: chosen warriors immune to pain.', phase3: 'FURY OF THE ALL-FATHER: Wild Hunt rides. Even gods fall silent. Sacrificed an eye for wisdom — worth it.', personality: 'Ancient, knowing, sacrificing. Sees all ends. Cold strategic mind. May test heroes himself.', domain: 'wisdom, death, magic, war', symbol: 'ravens, wolves, eight-legged horse, one eye, spear' },
  { id: 'thor', name: 'Thor', title: 'God of Thunder', pantheon: 'Norse', align: 'Chaotic good', hp: 399, AC: 4, MR: 80, phase1: 'Mjolnir: never misses when thrown, returns. 100 lightning bolts/day. Wind storm 90 yard radius.', phase2: 'Belt of strength doubles STR. Berserker rage: immune to all mind effects. Protects mortals.', phase3: 'STORM OF THUNDER: battlefield electrified, 10-100+16 damage each strike. Will fight Jormungandr at Ragnarok.', personality: 'Enormous, direct, protective of mortals. Genuinely likes people. Simple and devastating.', domain: 'thunder, strength, protection', symbol: 'hammer, goats, lightning, belt of strength' },
  { id: 'loki', name: 'Loki', title: 'Father of Monsters', pantheon: 'Norse', align: 'Chaotic evil', hp: 300, AC: -4, MR: 75, phase1: 'Perfect illusions at will. Immune to fire and charm. Fire bolt 6-60 damage. Shape change at will.', phase2: 'Summons Fenris Wolf AND Jormungandr simultaneously. No binding can hold him.', phase3: 'RAGNAROK TRIGGER: all Norse gods manifest, alignment-based — some fight FOR party. The end times begin.', personality: 'Gleefully malicious. Always three moves ahead. Finds your suffering entertaining. Causes Ragnarok.', domain: 'chaos, trickery, fire', symbol: 'snake, mistletoe, masks, nets' },
  { id: 'hel', name: 'Hel', title: 'Goddess of the Dishonored Dead', pantheon: 'Norse', align: 'Neutral evil', hp: 350, AC: -5, MR: 95, phase1: 'Half her face beautiful, half rotting corpse. Impervious to ALL physical weapons. Disease sword.', phase2: 'Withering wave: -20 HP all within 90 yards. Commands all dishonored dead.', phase3: 'REALM OF HEL SPREADS: cold spreads, darkness deepens, all warmth fades. No escape from her domain.', personality: 'Half beautiful, half rotting. Rules the dead. Patient. Has been waiting since always.', domain: 'death, disease, cold', symbol: 'half-living face, dishonored dead, darkness' },
  { id: 'freya', name: 'Freya', title: 'Goddess of Love and War', pantheon: 'Norse', align: 'Neutral good', hp: 339, AC: -3, MR: 80, phase1: '30th level fire spells. Brisingamen necklace: detects all lies within 30 yards. Falcon cloak: fly at will.', phase2: 'Half the battle dead are hers — she chooses first. Love and death are her domains equally.', phase3: 'VALKYRIE QUEEN: all slain warriors may be claimed. Fire and beauty burn together. Takes what she wants.', personality: 'Takes what she wants. Falcon-quick. Beautiful and fatal. Goddess of love AND war.', domain: 'love, war, beauty, death', symbol: 'necklace, falcon cloak, cats, boar' },
  { id: 'tyr', name: 'Tyr', title: 'God of Law and Justice', pantheon: 'Norse', align: 'Lawful good', hp: 380, AC: -5, MR: 25, phase1: 'Senses all thieves within 100 yards. Sees invisible. 25th paladin. One-handed: -2 AC but +2 damage.', phase2: 'Law domain: all oaths sworn in his name are binding. Divine judgment on lawbreakers.', phase3: 'SACRIFICE REMEMBERED: Fenrir bit off his hand — he placed it willingly. His word is absolute. Law made flesh.', personality: 'God of law and war. One-handed from feeding Fenrir. Sacrifice validated his word. Never lies.', domain: 'law, justice, war, sacrifice', symbol: 'severed hand, sword, scales, wolf' },
  { id: 'balder', name: 'Balder', title: 'The Beautiful', pantheon: 'Norse', align: 'Neutral good', hp: 388, AC: -4, MR: 75, phase1: 'Cannot be harmed by any weapon without mistletoe. Grants +2 CHA to any being met. Light presence: all shadows flee.', phase2: 'Beloved: all beings love him instinctively (save at -4 to act against him). Pure light made flesh.', phase3: 'RESURRECTED HOPE: even death could not hold him. Returns to bring light. The one exception to all rules.', personality: 'The Beautiful. Cannot be harmed by anything except mistletoe. Dies anyway. Beloved by all.', domain: 'light, beauty, joy, purity', symbol: 'mistletoe, light, white flowers' },

  // ═══════════════════════════════════════════════════════════════════════════
  // EGYPTIAN PANTHEON - 6 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'ra', name: 'Ra', title: 'Sun God', pantheon: 'Egyptian', align: 'Lawful good', hp: 400, AC: -2, MR: 95, phase1: 'Solar barge: travels any plane. Destroys undead on sight (no save). Commands all Egyptian gods.', phase2: 'Solar ray: 100 damage no save 1/round in sunlight. Light pierces all illusions.', phase3: 'SUN AT ZENITH: impossible to look upon. All enemies blinded and burning. Created himself.', personality: 'Ancient beyond measure, created himself. Protects order against chaos. Daily burden of existence made divine.', domain: 'sun, creation, kingship', symbol: 'sun disk, falcon, obelisk, scarab' },
  { id: 'osiris', name: 'Osiris', title: 'Lord of the Dead', pantheon: 'Egyptian', align: 'Lawful good', hp: 400, AC: -4, MR: 80, phase1: 'Judge of the dead. Can weigh any heart against truth. Crook and Flail +5 each.', phase2: 'Resurrects dead (unlimited). Grain grows wherever he walks. Hates Set with absolute and divine hatred.', phase3: 'LORD OF REBIRTH: all allies resurrected, all enemies judged. Murdered by Set and reborn. Understands death and renewal.', personality: 'Wise, just, murdered by Set and reborn. Judge of all Egyptian dead. Green skin, golden crown.', domain: 'death, rebirth, fertility, justice', symbol: 'crook and flail, djed pillar, green skin, white crown' },
  { id: 'isis', name: 'Isis', title: 'Mother of Magic', pantheon: 'Egyptian', align: 'Lawful good', hp: 350, AC: -2, MR: 75, phase1: 'Master of all magic: 30th MU. Resurrects Osiris yearly. Shape change at will.', phase2: 'Thousand names: recognized and worshipped in every culture. Knows all spells ever written.', phase3: 'QUEEN OF HEAVEN: her love for Osiris is older than civilization. Magic itself bows to her. No door is closed.', personality: 'Mother of magic. Fierce protector. Her love for Osiris defines her. Will do anything for those she loves.', domain: 'magic, motherhood, fertility, protection', symbol: 'throne, kite, sycamore, tiet (Isis knot)' },
  { id: 'set', name: 'Set', title: 'The Red Lord', pantheon: 'Egyptian', align: 'Lawful evil', hp: 378, AC: -4, MR: 59, phase1: 'Touch changes alignment permanently (no save). Poison skin: contact 3-18 damage. 30th illusionist.', phase2: 'Summons Apophis. Creates chaos storms. Desert winds blind and scour. Cannot be wounded by mortal weapons.', phase3: 'CHAOS UNBOUND: Reality warps. Spells have opposite effects. Only divine weapons work. Hates Osiris with divine hatred.', personality: 'Patient, implacable, certain of eventual victory. Killed his own brother. Embodies chaos and the desert.', domain: 'chaos, desert, storms, foreigners, evil', symbol: 'set animal, was scepter, red hair, desert' },
  { id: 'thoth', name: 'Thoth', title: 'God of Knowledge', pantheon: 'Egyptian', align: 'Neutral', hp: 389, AC: -4, MR: 98, phase1: '98% MR: effectively immune to magic. Scepter death touch. Negates any power within 100 yards 1/round.', phase2: 'Scribe of truth: knows all that is written and spoken. All knowledge: answers any question correctly.', phase3: 'MASTER OF WORDS: Reality is written, and he holds the pen. Can rewrite any fact. Utterly neutral. Judges nothing.', personality: 'God of knowledge and writing. Utterly neutral. Records all. Ibis-headed. Moon god. The mind of Egypt.', domain: 'knowledge, writing, magic, moon', symbol: 'ibis, baboon, writing palette, moon disk' },
  { id: 'ptah', name: 'Ptah', title: 'Creator God', pantheon: 'Egyptian', align: 'Lawful neutral', hp: 390, AC: -4, MR: 70, phase1: 'Created the Egyptian pantheon by thought alone. Scepter death spell at will.', phase2: 'Crafts anything: any item in 1 round. Truth-speaker: cannot be deceived by any being.', phase3: 'THE DIVINE CRAFTSMAN: thought made matter. Can unmake anything he has made. Reserved, ancient, precise.', personality: 'Creator god. Reserved, ancient, precise. Made the world as a craftsman makes a tool. Speaks through creation.', domain: 'creation, craftsmen, architects, truth', symbol: 'djed pillar, bull, mummiform' },

  // ═══════════════════════════════════════════════════════════════════════════
  // INDIAN PANTHEON - 4 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'shiva', name: 'Shiva', title: 'The Destroyer', pantheon: 'Indian', align: 'Neutral', hp: 450, AC: -10, MR: 90, phase1: 'Third eye: disintegrates any focused target (save at -6). Regenerates 10 HP/round.', phase2: 'Dance of Destruction: physics becomes optional in 500 yard radius. Pralaya: cosmic cycle begins to end.', phase3: 'THE END OF THE CYCLE: universe dissolves. Only those with divine blessing survive. Beyond morality.', personality: 'Both destroyer and benefactor. Compassionate yet terrible. Beyond mortal morality. The universe ends in his dance.', domain: 'destruction, transformation, meditation', symbol: 'third eye, trident, bull, moon, lingam' },
  { id: 'vishnu', name: 'Vishnu', title: 'The Preserver', pantheon: 'Indian', align: 'Lawful good', hp: 389, AC: -5, MR: 85, phase1: 'Makes any being unable to commit violence 30 yards (no save). Double-strength prismatic wall.', phase2: '10 avatars: appears in any form. Preservation: heals all within 60ft 2d10/round.', phase3: 'PRESERVER OF COSMIC ORDER: everything is his drama. All avatars manifest. The balance must be maintained.', personality: 'Patient, eternal, works through avatars. Everything is his drama. Will return as Kalki to end the age.', domain: 'preservation, order, righteousness', symbol: 'conch, discus, mace, lotus, eagle' },
  { id: 'indra', name: 'Indra', title: 'King of the Gods', pantheon: 'Indian', align: 'Chaotic neutral', hp: 400, AC: -12, MR: 80, phase1: 'Shield +4. Bow fires 2 lightning bolts/round at 1000 yard range. Flaming sword +3.', phase2: 'Vajra: divine thunderbolt kills outright (save at -4). Weather mastery: all storms answer.', phase3: 'KING OF DEVALOKA: all Vedic gods answer his call. Magnificent in battle. Soma-drinker. Proud warrior king.', personality: 'Proud warrior king. Soma-drinker. Magnificent in battle. Fought Vritra and won. Protector of the realm.', domain: 'thunder, rain, war, kingship', symbol: 'vajra, elephant, thunderbolt, rainbow' },
  { id: 'rudra', name: 'Rudra', title: 'The Howler', pantheon: 'Indian', align: 'Lawful neutral', hp: 344, AC: -2, MR: 25, phase1: 'Magic black bow: arrows cause rotting disease (death at -6 save). Creates and controls storms.', phase2: 'Storm mastery: weather in 500 mile radius. Healer\'s aspect: cures all disease (contradicts destroyer aspect).', phase3: 'THE STORM FATHER: Howls that shatter mountains. Both healer and destroyer. Shiva\'s fierce form.', personality: 'Storm and disease god. Healer and destroyer. Both equally. The Howler whose arrows bring death or cure.', domain: 'storm, disease, healing, hunt', symbol: 'bow, arrow, storm, deer' },

  // ═══════════════════════════════════════════════════════════════════════════
  // CELTIC PANTHEON - 3 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'dagda', name: 'The Dagda', title: 'Good God', pantheon: 'Celtic', align: 'Neutral', hp: 400, AC: -4, MR: 80, phase1: 'Cauldron of plenty: feeds unlimited beings, resurrects dead. Club: one end kills, other end resurrects.', phase2: 'Earth mastery: control terrain in 1 mile radius. Contracts never violated in his presence.', phase3: 'FATHER OF ALL: all Celtic gods answer his call. The land itself fights. Jolly, wise, terrifyingly powerful.', personality: 'Father of the gods. Jovial, enormous, terrifyingly powerful. Loves food. Good god means skilled, not moral.', domain: 'fertility, seasons, magic, protection', symbol: 'cauldron, club, harp, wheel' },
  { id: 'lugh', name: 'Lugh', title: 'The Many-Skilled', pantheon: 'Celtic', align: 'Neutral', hp: 375, AC: 0, MR: 90, phase1: 'Uses any attribute of any being he has ever met. Immune to control and petrification. 19th ranger.', phase2: 'Master of all crafts and skills: +5 any skill check. Spear never misses.', phase3: 'MASTER OF ALL ARTS: Every skill is his. Cannot be outmatched. The shining one. Samildanach.', personality: 'Versatile, proud, powerful. Respects all genuine craft. The shining one. Master of every art.', domain: 'skills, crafts, light, oaths', symbol: 'spear, sling, raven, hound' },
  { id: 'silvanus', name: 'Silvanus', title: 'Wild Lord of Nature', pantheon: 'Celtic', align: 'Neutral', hp: 333, AC: -4, MR: 30, phase1: 'Controls animals and plants by voice. Wolfhound companion (100HP, AC2). MV 48": fastest land movement.', phase2: 'Forest mastery: in forest, effectively omniscient. Knows all that occurs on the ground.', phase3: 'THE FOREST ITSELF: Older than the Celtic gods. The forest thinks through him. Wild lord absolute.', personality: 'Wild lord of nature. Older than the Celtic gods. The forest thinks through him. Neither good nor evil.', domain: 'wild nature, forests, animals', symbol: 'wolfhound, tree, club, wild man' },

  // ═══════════════════════════════════════════════════════════════════════════
  // CENTRAL AMERICAN PANTHEON - 3 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'quetzalcoatl', name: 'Quetzalcoatl', title: 'The Feathered Serpent', pantheon: 'Central American', align: 'Neutral good', hp: 400, AC: -8, MR: 90, phase1: 'Wind control. 30th MU. Feathered serpent form at will. Destroys evil on sight (no save for evil creatures).', phase2: 'Rebirth cycle: returns if slain. Solar fire from feathers. Cannot be deceived.', phase3: 'MORNING STAR RISES: all darkness banished. Evil creatures burn. Will return. Hates Tezcatlipoca.', personality: 'Ancient, paradoxical. Demands purity. Opposed to human sacrifice. Teacher of civilization. Will return.', domain: 'wind, wisdom, dawn, civilization', symbol: 'feathered serpent, morning star, quetzal bird, shell' },
  { id: 'tezcatlipoca', name: 'Tezcatlipoca', title: 'Smoking Mirror', pantheon: 'Central American', align: 'Chaotic evil', hp: 400, AC: -6, MR: 85, phase1: 'Smoking Mirror: sees all truth, cannot be surprised or deceived. Steals light: darkness in 500 yard radius.', phase2: 'Jaguar command: all jaguars serve him. Blood demand: steals HP from weakest target each round.', phase3: 'THE MIRROR JUDGES: all sins made manifest as enemies. Only the pure survive. Enemy of Quetzalcoatl.', personality: 'Ancient, testing, demands blood. The Smoking Mirror. Arbitrary, vengeful. Rival of Quetzalcoatl.', domain: 'night, sorcery, fate, jaguars', symbol: 'obsidian mirror, jaguar, smoking mirror, bone' },
  { id: 'tlaloc', name: 'Tlaloc', title: 'God of Rain', pantheon: 'Central American', align: 'Neutral', hp: 400, AC: -4, MR: 65, phase1: 'Lightning bolt 40 damage at will. 4 magic water pitchers (any weather effect). Rain mastery.', phase2: 'Drought and flood: landscape control in 100 miles. All water answers.', phase3: 'STORM OF THE AGES: Lightning never stops. Rain drowns or withers at will. Demands child sacrifice.', personality: 'Rain god. Demands child sacrifice. Does not enjoy it. Requires it nonetheless. Goggle-eyed, fanged.', domain: 'rain, lightning, agriculture, drought', symbol: 'goggle eyes, fangs, water jug, lightning' },

  // ═══════════════════════════════════════════════════════════════════════════
  // FINNISH PANTHEON - 2 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'ukko', name: 'Ukko', title: 'Sky Father', pantheon: 'Finnish', align: 'Lawful good', hp: 400, AC: -2, MR: 85, phase1: 'Flaming sword: death spell on hit (save at -6). Hammer of thunder: 10d10 area damage.', phase2: 'Weather mastery: controls all weather. Supreme Finnish god: commands all Finnish pantheon.', phase3: 'STORM FATHER UNLEASHED: The sky is his domain. All storms answer. 85% MR. Stern but fair.', personality: 'Sky father. Stern but fair. The storm has his face. Commands all Finnish gods.', domain: 'sky, thunder, weather, harvest', symbol: 'hammer, sword, cloud, eagle' },
  { id: 'ahto', name: 'Ahto', title: 'Sea King', pantheon: 'Finnish', align: 'Neutral good', hp: 324, AC: 2, MR: 100, phase1: '100% MR in water. Wind and water spells at will. Sickle +4: 2-20 damage.', phase2: 'Commands all sea creatures. Knows all that occurs in water anywhere. Swim unlimited.', phase3: 'OCEAN MASTER: In water, invincible. Generous to sailors who honor him. Merciless to those who don\'t.', personality: 'Sea king. Generous to sailors who honor him. Merciless to those who don\'t. Knows all water secrets.', domain: 'sea, fish, wisdom, healing', symbol: 'sickle, water, fish, reed' },

  // ═══════════════════════════════════════════════════════════════════════════
  // JAPANESE PANTHEON - 2 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'amaterasu', name: 'Amaterasu', title: 'Sun Goddess', pantheon: 'Japanese', align: 'Lawful good', hp: 400, AC: -2, MR: 85, phase1: 'Solar goddess: immune to darkness and blindness. Mirror: reflects any magical attack back at caster.', phase2: 'Light of truth: all deception fails in her presence. Commands all Japanese gods.', phase3: 'SUN GODDESS ASCENDANT: The world goes dark without her. Light burns all impurity. Righteous, beautiful.', personality: 'Sun goddess. Righteous, beautiful, occasionally retreats. The world goes dark when she hides.', domain: 'sun, light, truth, rulership', symbol: 'mirror, sun, rooster, weaving' },
  { id: 'izanagi', name: 'Izanagi', title: 'Father Creator', pantheon: 'Japanese', align: 'Lawful good', hp: 375, AC: -3, MR: 70, phase1: 'Creator of Japan: earth obeys him. Purification ritual cleanses any evil.', phase2: 'Death immunity: has died and returned. Commands all Japanese gods.', phase3: 'THE PRIMORDIAL FATHER: Created the land itself. Formal, ancient, bound by grief. Lost his wife. Keeps working.', personality: 'Father creator. Formal, ancient, bound by grief. Lost his wife Izanami. Keeps working. Brought death into the world.', domain: 'creation, life, death, purification', symbol: 'spear, jewels, death, birth' },

  // ═══════════════════════════════════════════════════════════════════════════
  // BABYLONIAN PANTHEON - 1 Greater God
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'marduk', name: 'Marduk', title: 'King of the Gods', pantheon: 'Babylonian', align: 'Lawful neutral', hp: 350, AC: 1, MR: 50, phase1: 'Borrows any deity ability in pantheon (no save). Silvery net binds any being (no save).', phase2: 'Commands all Babylonian gods. Storm spells at 40th level effectiveness.', phase3: 'KING OF BABYLON: All Babylonian gods answer. Fair, powerful, expects proper worship. Defeated Tiamat.', personality: 'Supreme Babylonian god. Fair, powerful, expects proper worship. Defeated Tiamat. Created Babylon.', domain: 'kingship, order, storms, wisdom', symbol: 'mušḫuššu, spear, net, tablet of destinies' },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEHWON PANTHEON - 2 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'kos', name: 'Kos', title: 'God of Battle', pantheon: 'Nehwon', align: 'Neutral', hp: 377, AC: -4, MR: 35, phase1: 'Summons 9-90 berserkers per day. Broadsword +6. Battle judge: decides outcome of single combats.', phase2: 'Destroys cowards among worshipers. All warriors fear his judgment.', phase3: 'BATTLE INCARNATE: Simple, fierce, respects only courage. Punishes cowardice with death.', personality: 'God of battle. Simple, fierce, respects only courage. Punishes cowardice with death.', domain: 'battle, courage, judgment', symbol: 'broadsword, shield, blood, crown' },
  { id: 'death_nehwon', name: 'Death', title: 'The End of All Things', pantheon: 'Nehwon', align: 'Neutral', hp: 350, AC: -5, MR: 95, phase1: '10 attacks/round: each touch requires save vs. death. Sword slays anything it touches.', phase2: 'On Nehwon all beings mortal including Death himself (unique vulnerability). Cannot be permanently destroyed on Nehwon.', phase3: 'DEATH HIMSELF: Patient, inevitable, surprisingly conversational. Mortal on Nehwon. The end comes for all.', personality: 'Death himself. Patient, inevitable, surprisingly conversational. On Nehwon: mortal. The end comes for all.', domain: 'death, endings, inevitability', symbol: 'scythe, hourglass, skull, black robe' },

  // ═══════════════════════════════════════════════════════════════════════════
  // NONHUMAN PANTHEON - 3 Greater Gods
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'moradin', name: 'Moradin', title: 'Soul Forger', pantheon: 'Nonhuman', align: 'Lawful good', hp: 400, AC: -7, MR: 80, phase1: 'Soul Forger: reshapes any metallic being at will. Crafts indestructible divine weapons.', phase2: 'All dwarves +1 saves in his presence. Forge mastery: creates any item instantly.', phase3: 'FATHER OF DWARVES: Stern, fair, values craft and dedication. Clan-bound. The forge is his heart.', personality: 'Father of dwarves. Stern, fair, values craft and dedication. Clan-bound. Created the dwarves.', domain: 'forge, creation, protection, dwarves', symbol: 'hammer, anvil, forge, ale' },
  { id: 'corellon', name: 'Corellon Larethian', title: 'Creator of the Elves', pantheon: 'Nonhuman', align: 'Chaotic good', hp: 400, AC: -5, MR: 90, phase1: 'Arrows never miss. Banishes demons and devils on sight. Art blessing: any creation in his presence is masterwork.', phase2: 'All elves +1 all saves in his presence. Beauty and grace incarnate.', phase3: 'ELVEN FATHER: Beautiful, ancient, protective. Made the elves from his own blood. Art and magic are his gifts.', personality: 'Elven father. Beautiful, ancient, protective. Made the elves from his own blood. Patron of art and magic.', domain: 'art, magic, music, elves', symbol: 'longbow, crescent moon, star, harp' },
  { id: 'gruumsh', name: 'Gruumsh', title: 'One-Eyed God', pantheon: 'Nonhuman', align: 'Lawful evil', hp: 350, AC: -3, MR: 75, phase1: 'Iron spear +5: 3-30+10, paralysis on hit. Paralyzes all orcs within sight who displease him.', phase2: 'One-eyed: -2 to hit but +4 damage. All orcs serve him without question.', phase3: 'ORC FATHER: Hateful, powerful, demands endless war. The other gods took his land. He will take it back.', personality: 'Orc god. Hateful, powerful, demands endless war. The other gods took his land. Never forgets.', domain: 'war, conquest, orcs, hatred', symbol: 'spear, one eye, blood, flame' },

  // ═══════════════════════════════════════════════════════════════════════════
  // MELNIBONÉAN PANTHEON - 1 Greater God
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'arioch', name: 'Arioch', title: 'Lord of the Seven Darks', pantheon: 'Melnibonéan', align: 'Chaotic evil', hp: 350, AC: -3, MR: 70, phase1: 'Chaos blade: 3-30+9 damage, dispels any magic item on hit. Patron of Elric: appears when Ring of Kings invoked.', phase2: 'Chaos energy: all saves at -2 in his presence. Soul drain: kills any being below 5 HP instantly.', phase3: 'LORD OF CHAOS: all order-based magic reverses. Law becomes suffering. Ancient evil, bound by compact.', personality: 'Elegant, cruel, fulfills contracts exactly as worded with horrific results. Patron of the last Melnibonean emperor.', domain: 'chaos, contracts, vengeance', symbol: 'chaos star, eight arrows, black sword' },

  // ═══════════════════════════════════════════════════════════════════════════
  // CTHULHU MYTHOS - 2 Greater Gods (technically Outer Gods/Great Old Ones)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: 'cthulhu', name: 'Cthulhu', title: 'The Dreamer', pantheon: 'Cthulhu', align: 'Chaotic evil', hp: 400, AC: -4, MR: 75, phase1: 'Insanity gaze: WIS save -6 or lose 1d4 WIS permanently. 15 tentacles 3-30 each.', phase2: 'Psychic scream: all within 200yd save vs. death or catatonic. Regen 10HP/round. Dreams leak into reality.', phase3: 'RISING FROM RLYEH: immune to weapons, only faith-based or opposing-align attacks work. Not malevolent. Incomprehensible.', personality: 'Not malevolent. Simply incomprehensible. Your existence is irrelevant to it. Dreams in R\'lyeh.', domain: 'dreams, madness, the deep', symbol: 'stars, water, tentacles, madness' },
  { id: 'nyarlathotep', name: 'Nyarlathotep', title: 'The Crawling Chaos', pantheon: 'Cthulhu', align: 'Chaotic evil', hp: 350, AC: -4, MR: 85, phase1: 'Thousand forms. Can appear as anything. Charm 1-100 humans/humanoids on sight (no save). Drains 3-30 HP each hit.', phase2: 'Infects dreams with madness. Summons shoggoths and nightgaunts. Reality bleeds nightmare. Messenger of Outer Gods.', phase3: 'THE MESSENGER SPEAKS: all who hear understand truth and go mad. The only Outer God who enjoys interacting with mortals.', personality: 'Cruel, theatrical, patient. The only Outer God who enjoys interacting with mortals. Serves alien masters cheerfully.', domain: 'chaos, messenger, madness, masks', symbol: 'masks, shadows, chaos, infinite forms' }
]

// ═══════════════════════════════════════════════════════════════════════════
// ANTAGONIST CLUE SYSTEM - Identity revealed progressively through Acts
// ═══════════════════════════════════════════════════════════════════════════

// (AntagonistClue interface is now in @/lib/gameTypes.ts)

export const ANTAGONIST_CLUES: AntagonistClue[] = [
  // === ACT I CLUES - Very vague, just hints of shadow and power ===
  { id: 'clue_1_01', act: 1, clue_text: 'The shadow falls long across the world, and in that shadow, small things stop moving. Something ancient stirs.', reveals: 'shadow', specificity: 'vague', trigger: 'Opening scene' },
  { id: 'clue_1_02', act: 1, clue_text: 'There is a presence watching. Not with eyes—something older than eyes. It has been patient.', reveals: 'shadow', specificity: 'vague', trigger: 'First NPC encounter' },
  { id: 'clue_1_03', act: 1, clue_text: 'The gods speak of a disturbance. One of their own moves against the order. They will not say who.', reveals: 'shadow', specificity: 'vague', trigger: 'Any god encounter' },
  { id: 'clue_1_04', act: 1, clue_text: 'Animals flee. The wind carries the scent of something that should not be.', reveals: 'shadow', specificity: 'vague', trigger: 'Exploration' },
  { id: 'clue_1_05', act: 1, clue_text: 'The shard pulses warmer when [PANTHEON] names are spoken. It knows its enemy.', reveals: 'pantheon', specificity: 'vague', trigger: 'Shard interaction' },
  { id: 'clue_1_06', act: 1, clue_text: 'In dreams, the party sees a figure on a throne. The throne\'s shape hints at origins older than Greece.', reveals: 'pantheon', specificity: 'vague', trigger: 'Rest' },
  { id: 'clue_1_07', act: 1, clue_text: 'The antagonist is known to all pantheons. Feared by some. Respected by others.', reveals: 'shadow', specificity: 'vague', trigger: 'Conversation with sage' },
  { id: 'clue_1_08', act: 1, clue_text: 'Whatever hunts the shard, it has done so before. Many times. Through many ages.', reveals: 'shadow', specificity: 'vague', trigger: 'End of Act I' },
  
  // === ACT II CLUES - Moderate specificity, domain and pantheon hints ===
  { id: 'clue_2_01', act: 2, clue_text: 'The antagonist\'s power is tied to [DOMAIN]. Where that power waxes, they grow stronger.', reveals: 'domain', specificity: 'moderate', trigger: 'Act II opening' },
  { id: 'clue_2_02', act: 2, clue_text: 'A symbol appears in scattered ruins: [SYMBOL]. It is their mark, left across centuries.', reveals: 'symbol', specificity: 'moderate', trigger: 'Exploration' },
  { id: 'clue_2_03', act: 2, clue_text: 'The [PANTHEON] gods grow tense when the antagonist\'s presence is mentioned.', reveals: 'pantheon', specificity: 'moderate', trigger: 'Pantheon god encounter' },
  { id: 'clue_2_04', act: 2, clue_text: 'Their alignment is [ALIGNMENT]. They work through chaos/order to achieve their ends.', reveals: 'alignment', specificity: 'moderate', trigger: 'Observation of effects' },
  { id: 'clue_2_05', act: 2, clue_text: '"I have fought them before," says an old god. "They are of the [PANTHEON], but answer to their own nature."', reveals: 'pantheon', specificity: 'moderate', trigger: 'Quest reward' },
  { id: 'clue_2_06', act: 2, clue_text: 'The antagonist\'s name begins with the letter [FIRST_LETTER]. This much an oracle reveals.', reveals: 'name_fragment', specificity: 'moderate', trigger: 'Oracle/conversation' },
  { id: 'clue_2_07', act: 2, clue_text: 'In their domain of [DOMAIN], they are absolute. Mortal weapons mean nothing.', reveals: 'domain', specificity: 'moderate', trigger: 'Combat encounter' },
  { id: 'clue_2_08', act: 2, clue_text: 'The shard\'s bearer dreams of [VISUAL_HINT]—the antagonist\'s true form, glimpsed in nightmare.', reveals: 'symbol', specificity: 'moderate', trigger: 'End of Act II' },
  
  // === ACT III CLUES - Specific, near-full reveal ===
  { id: 'clue_3_01', act: 3, clue_text: 'The antagonist is [NAME], the [TITLE]. Their identity is no longer hidden.', reveals: 'identity', specificity: 'specific', trigger: 'Act III opening' },
  { id: 'clue_3_02', act: 3, clue_text: '"I am [NAME]. You have carried my shard across the world, and now you will return it—or die."', reveals: 'identity', specificity: 'specific', trigger: 'First boss phase' },
  { id: 'clue_3_03', act: 3, clue_text: 'The symbols of [SYMBOL] blaze in the sky. There can be no doubt.', reveals: 'identity', specificity: 'specific', trigger: 'Boss phase 2' },
  { id: 'clue_3_04', act: 3, clue_text: '[PANTHEON] gods arrive to witness. "So [NAME] has revealed themselves at last."', reveals: 'identity', specificity: 'specific', trigger: 'Divine intervention' },
  { id: 'clue_3_05', act: 3, clue_text: 'In the final battle, [NAME]\'s power is absolute within their domain. Only [COUNTER] can defeat them.', reveals: 'identity', specificity: 'specific', trigger: 'Boss phase 3' },
  { id: 'clue_3_06', act: 3, clue_text: 'The shard screams with recognition. It was theirs, once, before it was lost.', reveals: 'identity', specificity: 'specific', trigger: 'Shard interaction' },
  { id: 'clue_3_07', act: 3, clue_text: 'All clues assemble: [PANTHEON], [DOMAIN], [SYMBOL], [NAME]. The picture is complete.', reveals: 'identity', specificity: 'specific', trigger: 'Puzzle/ritual' },
  { id: 'clue_3_08', act: 3, clue_text: '"You know who I am now. Good. I prefer my enemies to know the face of their end." — [NAME]', reveals: 'identity', specificity: 'specific', trigger: 'Final confrontation' }
]
