#!/usr/bin/env python3
"""add_zai_metadata.py - Add Z.ai metadata to a PDF file."""
import sys
import os

def add_metadata(filepath: str):
    from PyPDF2 import PdfReader, PdfWriter
    reader = PdfReader(filepath)
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    # Derive title from filename if possible
    base = os.path.basename(filepath).replace('.pdf', '').replace('_', ' ')
    title = base if base else 'Z.ai Document'
    writer.add_metadata({
        '/Title': title,
        '/Author': 'Z.ai',
        '/Creator': 'Z.ai',
        '/Producer': 'Z.ai',
        '/Subject': f'{title} - Generated by Z.ai',
    })
    out = filepath  # overwrite in place
    with open(out, 'wb') as f:
        writer.write(f)
    print(f"Metadata added to: {out}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python add_zai_metadata.py <pdf_file>")
        sys.exit(1)
    add_metadata(sys.argv[1])
